-- =============================================================================
-- Phase 8 — Banking Industry Accelerator
-- Real etl.ctrl_pipeline_metadata rows for the four objects
-- tools/synthetic-data-generator actually produces, superseding the single
-- illustrative row from src/sql/09-seed-data/02_Seed_Pipeline_Metadata_Example.sql
-- (that row references a source_system.csv the generator doesn't produce —
-- left in place as a minimal-shape example, not removed).
--
-- load_priority enforces FK order: customer must load before account/loan
-- (both FK to dim_customer), which must load before transaction (FK to
-- dim_account via account_id). All FULL loads — the generator regenerates
-- a full snapshot each run, not incremental deltas.
-- =============================================================================

USE [AdeaDW];
GO

IF NOT EXISTS (SELECT 1 FROM dim.dim_source_system WHERE source_system_code = 'BANKING_CORE')
BEGIN
    INSERT INTO dim.dim_source_system (source_system_code, source_system_name, description)
    VALUES ('BANKING_CORE', 'Banking Core (synthetic)', 'Generated by tools/synthetic-data-generator''s banking domain.');
END
GO

MERGE etl.ctrl_pipeline_metadata AS tgt
USING (VALUES
    ('BANKING_CORE', 'banking_customer',    10, 'FULL', 'raw', 'banking', 'customers.csv',    'staging', 'stg_banking_customer',    'etl.usp_load_dim_customer_banking'),
    ('BANKING_CORE', 'banking_account',     20, 'FULL', 'raw', 'banking', 'accounts.csv',      'staging', 'stg_banking_account',     'etl.usp_load_dim_account'),
    ('BANKING_CORE', 'banking_loan',        20, 'FULL', 'raw', 'banking', 'loans.csv',         'staging', 'stg_banking_loan',        'etl.usp_load_dim_loan'),
    ('BANKING_CORE', 'banking_transaction', 30, 'FULL', 'raw', 'banking', 'transactions.csv',  'staging', 'stg_banking_transaction', 'etl.usp_load_fact_transactions_banking')
) AS src (
    source_system, object_name, load_priority, load_type,
    source_container, source_folder_path, source_file_name,
    sink_schema, sink_table, load_procedure_name
)
ON tgt.source_system = src.source_system AND tgt.object_name = src.object_name
WHEN MATCHED THEN UPDATE SET
    load_priority = src.load_priority,
    load_type = src.load_type,
    source_container = src.source_container,
    source_folder_path = src.source_folder_path,
    source_file_name = src.source_file_name,
    sink_schema = src.sink_schema,
    sink_table = src.sink_table,
    load_procedure_name = src.load_procedure_name,
    updated_date = SYSUTCDATETIME(),
    updated_by = SUSER_SNAME()
WHEN NOT MATCHED BY TARGET THEN INSERT (
    source_system, object_name, load_priority, load_type,
    source_container, source_folder_path, source_file_name,
    sink_schema, sink_table, load_procedure_name
)
VALUES (
    src.source_system, src.object_name, src.load_priority, src.load_type,
    src.source_container, src.source_folder_path, src.source_file_name,
    src.sink_schema, src.sink_table, src.load_procedure_name
);
GO
