-- =============================================================================
-- Phase 8 — Retail Industry Accelerator
-- Real etl.ctrl_pipeline_metadata rows for the four objects
-- tools/synthetic-data-generator's retail domain produces. customer and
-- product are independent (both priority 10); order depends on both
-- (priority 20, FK to dim_customer and dim_product); inventory depends
-- only on product (priority 20 also — no FK dependency between order and
-- inventory, so they can run in either order relative to each other, same
-- "same tier, no relative ordering needed" situation as banking's
-- account/loan). All FULL loads.
-- =============================================================================

USE [AdeaDW];
GO

IF NOT EXISTS (SELECT 1 FROM dim.dim_source_system WHERE source_system_code = 'RETAIL_CORE')
BEGIN
    INSERT INTO dim.dim_source_system (source_system_code, source_system_name, description)
    VALUES ('RETAIL_CORE', 'Retail Core (synthetic)', 'Generated by tools/synthetic-data-generator''s retail domain.');
END
GO

MERGE etl.ctrl_pipeline_metadata AS tgt
USING (VALUES
    ('RETAIL_CORE', 'retail_customer',  10, 'FULL', 'raw', 'retail', 'customers.csv', 'staging', 'stg_retail_customer',  'etl.usp_load_dim_customer_retail'),
    ('RETAIL_CORE', 'retail_product',   10, 'FULL', 'raw', 'retail', 'products.csv',  'staging', 'stg_retail_product',   'etl.usp_load_dim_product_retail'),
    ('RETAIL_CORE', 'retail_order',     20, 'FULL', 'raw', 'retail', 'orders.csv',    'staging', 'stg_retail_order',     'etl.usp_load_fact_orders_retail'),
    ('RETAIL_CORE', 'retail_inventory', 20, 'FULL', 'raw', 'retail', 'inventory.csv', 'staging', 'stg_retail_inventory', 'etl.usp_load_fact_inventory_retail')
) AS src (
    source_system, object_name, load_priority, load_type,
    source_container, source_folder_path, source_file_name,
    sink_schema, sink_table, load_procedure_name
)
ON tgt.source_system = src.source_system AND tgt.object_name = src.object_name
WHEN MATCHED THEN UPDATE SET
    load_priority = src.load_priority,
    load_type = src.load_type,
    source_container = src.source_container,
    source_folder_path = src.source_folder_path,
    source_file_name = src.source_file_name,
    sink_schema = src.sink_schema,
    sink_table = src.sink_table,
    load_procedure_name = src.load_procedure_name,
    updated_date = SYSUTCDATETIME(),
    updated_by = SUSER_SNAME()
WHEN NOT MATCHED BY TARGET THEN INSERT (
    source_system, object_name, load_priority, load_type,
    source_container, source_folder_path, source_file_name,
    sink_schema, sink_table, load_procedure_name
)
VALUES (
    src.source_system, src.object_name, src.load_priority, src.load_type,
    src.source_container, src.source_folder_path, src.source_file_name,
    src.sink_schema, src.sink_table, src.load_procedure_name
);
GO
