-- =============================================================================
-- Phase 8 — Healthcare Industry Accelerator
-- Real etl.ctrl_pipeline_metadata rows for the four objects
-- tools/synthetic-data-generator's healthcare domain produces. Same
-- load_priority pattern as examples/banking/sql/07_Seed_Pipeline_Metadata_Banking.sql:
-- patient and provider are independent (both priority 10, no FK between
-- them), claim and pharmacy both depend on patient AND provider (priority
-- 20). All FULL loads — the generator regenerates a full snapshot each run.
-- =============================================================================

USE [AdeaDW];
GO

IF NOT EXISTS (SELECT 1 FROM dim.dim_source_system WHERE source_system_code = 'HEALTHCARE_CORE')
BEGIN
    INSERT INTO dim.dim_source_system (source_system_code, source_system_name, description)
    VALUES ('HEALTHCARE_CORE', 'Healthcare Core (synthetic)', 'Generated by tools/synthetic-data-generator''s healthcare domain.');
END
GO

MERGE etl.ctrl_pipeline_metadata AS tgt
USING (VALUES
    ('HEALTHCARE_CORE', 'healthcare_patient',  10, 'FULL', 'raw', 'healthcare', 'patients.csv',  'staging', 'stg_healthcare_patient',  'etl.usp_load_dim_patient_healthcare'),
    ('HEALTHCARE_CORE', 'healthcare_provider', 10, 'FULL', 'raw', 'healthcare', 'providers.csv', 'staging', 'stg_healthcare_provider', 'etl.usp_load_dim_provider_healthcare'),
    ('HEALTHCARE_CORE', 'healthcare_claim',    20, 'FULL', 'raw', 'healthcare', 'claims.csv',    'staging', 'stg_healthcare_claim',    'etl.usp_load_fact_claims_healthcare'),
    ('HEALTHCARE_CORE', 'healthcare_pharmacy', 20, 'FULL', 'raw', 'healthcare', 'pharmacy.csv',  'staging', 'stg_healthcare_pharmacy', 'etl.usp_load_fact_pharmacy_healthcare')
) AS src (
    source_system, object_name, load_priority, load_type,
    source_container, source_folder_path, source_file_name,
    sink_schema, sink_table, load_procedure_name
)
ON tgt.source_system = src.source_system AND tgt.object_name = src.object_name
WHEN MATCHED THEN UPDATE SET
    load_priority = src.load_priority,
    load_type = src.load_type,
    source_container = src.source_container,
    source_folder_path = src.source_folder_path,
    source_file_name = src.source_file_name,
    sink_schema = src.sink_schema,
    sink_table = src.sink_table,
    load_procedure_name = src.load_procedure_name,
    updated_date = SYSUTCDATETIME(),
    updated_by = SUSER_SNAME()
WHEN NOT MATCHED BY TARGET THEN INSERT (
    source_system, object_name, load_priority, load_type,
    source_container, source_folder_path, source_file_name,
    sink_schema, sink_table, load_procedure_name
)
VALUES (
    src.source_system, src.object_name, src.load_priority, src.load_type,
    src.source_container, src.source_folder_path, src.source_file_name,
    src.sink_schema, src.sink_table, src.load_procedure_name
);
GO
